
OBJ_FILE = $(wildcard $(OBJ_DIR)/*.o)

.PHONY: all subdir static_lib dynamic_lib

all: subdir static_lib dynamic_lib 

static_lib:
	$(AR) rcs $(STATIC_NAME) $(OBJ_FILE)

dynamic_lib:
	$(CC) -shared -o $(DYNAMIC_NAME) $(OBJ_FILE)

subdir:
	$(MAKE) -C $(IPCS_DIR) CFLAGS="$(CFLAGS)" OBJ_DIR=$(OBJ_DIR) CC=$(CC) AR=$(AR)
	$(MAKE) -C $(NET_DIR)  CFLAGS="$(CFLAGS)" OBJ_DIR=$(OBJ_DIR) CC=$(CC) AR=$(AR)
	$(MAKE) -C $(UTIL_DIR) CFLAGS="$(CFLAGS)" OBJ_DIR=$(OBJ_DIR) CC=$(CC) AR=$(AR)

